name: Create upstream pull request

on:
  push:
    branches:
      - "release_*"

jobs:
  push:
    name: Push Event
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Jira Processing
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          npm install node-fetch
          npm install fs
          node scripts/jira-comment.js
