name: Create upstream pull request
on:
  push:
    branches:
      - "*"

jobs:
  push:
    name: Push Event
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Jira Processing
        run: |
          npm install node-fetch
          npm install fs
          npm install util.promisify
          npm install dotenv
          node scripts/jira-comment.js
