name: Create upstream pull request
on:
  push:
    branches:
      - "*"

jobs:
  push:
    name: Push Event
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
      - name: Merge to Master and Create GitHub Release
        run: |
          node scripts/jira.js
