name: Create upstream pull request
on:
  pull_request:
    branches:
      - release_*
    types: [closed]

jobs:
  generate-matrix:
    name: Generate matrix for merge action of ${{  github.head_ref }}
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.body, '/release-train-bug-fix')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - name: Set matrix for build
        id: set-matrix
        run: |
          npm install compare-versions
          (( $(( (`date +\%s` / 604800 + 1) % 2 )) )) && node scripts/upstream_list.js ${{ github.base_ref }} ${{  github.head_ref }}
          echo "::set-output name=matrix::$( node scripts/upstream_list.js ${{ github.base_ref }} )"
  merge-upstream-release:
    name: Merge ${{  github.head_ref }} to Upstream Release "${{ matrix.upstream_release }}"
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.body, '/release-train-bug-fix')
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge ${{  github.head_ref }} -> ${{ matrix.upstream_release }}
        if:   ${{ matrix.upstream_release }} != ''
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{  github.head_ref }}
          target_branch: ${{ matrix.upstream_release }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  merge-to-develop:
    name: Merge ${{  github.head_ref }} to Develop Branch
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.body, '/release-train-bug-fix')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge ${{  github.head_ref }} -> develop
        if:   ${{ matrix.upstream_release }} != ''
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{  github.head_ref }}
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}

